name: Build Library

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./CSCore
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_TOKEN }}
    - name: Restore Nuget
      run: nuget restore CSCore.csproj
    - name: Build Solution
      run: |
        msbuild.exe CSCore.csproj /nologo
