name: Build Library

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x'
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_TOKEN }}
    - name: Install .NET Framework 4.0/4.5 Developer Packs
      run: |
        choco install netfx-4.0.1-devpack -y
        choco install netfx-4.5.2-devpack -y
    - name: Restore Nuget
      run: nuget restore CSCore.sln
    - name: Build Solution
      run: |
        msbuild.exe CSCore.sln /p:Platform="Any CPU" /p:Configuration=Release
